version: '3.9'
services:
  api:
    container_name: eda-api-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '5001:5001'
    env_file:
      - .env