name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23'

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Update repository on server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "Connecting to $SERVER_USER@$SERVER_HOST on port 22 using sshpass"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -p 22 $SERVER_USER@$SERVER_HOST 'cd project/eda/ && git pull && docker-compose up -d --build --no-deps api && docker system prune -a -f'